import type { Reference } from "./references";

/**
 * Knowledge Hub recipes.
 *
 * Each recipe files under its own dish name in the A-Z, and also under the
 * first letter of its `tag`, so every salad is reachable from S whatever it
 * is called.
 */
export type Recipe = {
  slug: string;
  title: string;
  /** Dish type, e.g. "Salad". Also gives the recipe a second letter in the A-Z. */
  tag: string;
  category: string;
  summary: string;
  keyPoints?: string[];
  image?: string;
  imageAlt?: string;
  imageCredit?: string;
  serves: string;
  prepTime: string;
  /** ISO 8601 duration, for Recipe structured data. */
  prepTimeIso: string;
  intro: string[];
  ingredients: { group?: string; items: string[] }[];
  method: string[];
  notes?: string[];
  relatedTopics: string[];
  guides: string[];
  references?: Reference[];
};

export const recipes: Recipe[] = [
  {
    slug: "cucumber-potato-dill-salad",
    title: "Cucumber, potato and dill salad",
    tag: "Salad",
    category: "Food & energy",
    summary:
      "A cool, no-fuss salad for a hot afternoon. Nothing to cook but the potatoes, and it is better made ahead.",
    keyPoints: [
      "Serves 4, ready in about 20 minutes plus chilling.",
      "Only the potatoes need cooking, so it suits a hot day.",
      "Chickpeas turn it from a side dish into a light meal.",
      "Curd works perfectly well in place of Greek yogurt.",
      "Better made an hour ahead, so it is useful when people are coming.",
    ],
    serves: "4",
    prepTime: "20 minutes, plus 30 minutes chilling",
    prepTimeIso: "PT20M",
    intro: [
      "This is a classic combination in German, Scandinavian and Eastern European cooking, where potato, cucumber and dill turn up together all summer. Dill will be familiar to you as suva or shepu, and it is what makes the dish taste like itself, so do not leave it out.",
      "It suits a hot afternoon because nothing needs cooking except the potatoes, and it improves for sitting in the fridge an hour, which makes it a genuinely useful thing to have in your repertoire when people are coming.",
    ],
    ingredients: [
      {
        items: [
          "2 medium potatoes, boiled and cut into bite-sized cubes",
          "1 large cucumber, thinly sliced",
          "1 tin of chickpeas, drained and rinsed, or a cupful cooked",
          "2 to 3 tbsp fresh dill (suva), chopped",
          "1 small red onion, thinly sliced (optional)",
        ],
      },
      {
        group: "For the dressing",
        items: [
          "2 tbsp thick curd, hung curd or Greek yogurt",
          "1 tbsp mustard: wholegrain or Dijon if you have it, otherwise a teaspoon of mustard paste or kasundi",
          "1 tbsp olive oil",
          "1 tbsp lemon juice",
          "Salt and freshly ground black pepper",
        ],
      },
    ],
    method: [
      "Boil the potatoes until just tender, no further, or they will break up when you toss them. Let them cool a little, then cut into bite-sized cubes.",
      "Slice the cucumber thinly. For a crunchier salad, salt the slices lightly, leave them for ten minutes, then pat them dry, which draws out some of the water.",
      "Whisk the curd, mustard, olive oil and lemon juice together with a good pinch of salt and plenty of black pepper. Taste it now, while you can still adjust it.",
      "Tip the potatoes, cucumber, chickpeas, dill and onion into a bowl and fold the dressing through gently.",
      "Chill for twenty to thirty minutes before serving. It will taste better than it did when you mixed it.",
    ],
    notes: [
      "The chickpeas are what make this a light meal rather than a side dish, and they bring protein and fibre with them. Worth putting in rather than treating as optional.",
      "A handful of toasted pumpkin or sunflower seeds on top adds crunch and a little more protein.",
      "If you are watching your blood sugar, keep the potato modest and let the chickpeas and vegetables do more of the work, and eat it alongside something with protein rather than on its own.",
      "Paneer, crumbled over, works well in place of the feta this is often made with.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "anti-inflammatory-swaps-indian-kitchen",
      "prebiotics-and-probiotics",
    ],
    guides: [],
  },
  {
    slug: "coffee-chocolate-mug-cake",
    title: "Coffee and chocolate mug cake",
    tag: "Dessert",
    category: "Food & energy",
    summary:
      "Eggless, made with rice flour, and ready in about five minutes in a mug. A treat, and honestly labelled as one.",
    keyPoints: [
      "Serves one, and about five minutes from cupboard to spoon.",
      "Eggless, and gluten-free if your rice flour is.",
      "Baking powder gives the best rise. Baking soda on its own will not work here.",
      "No oven needed: a microwave, or steamed in a dosa maker or covered pan.",
      "This is a treat rather than an everyday food. One mug, now and then.",
    ],
    serves: "1",
    prepTime: "5 minutes",
    prepTimeIso: "PT5M",
    intro: [
      "Sometimes you want something sweet and you want it now, and the alternative is a packet of biscuits. This takes about five minutes, uses what is already in most Indian kitchens, needs no oven and no eggs, and it comes out as a single portion, which is rather the point.",
      "It is a treat. There is sugar in it and rice flour is a refined carbohydrate, so this belongs with the sweets that are for occasions rather than with everyday eating. Having it in a mug settles the portion question by itself.",
    ],
    ingredients: [
      {
        items: [
          "1/2 cup rice flour",
          "1 tbsp cocoa powder",
          "1 tsp instant coffee",
          "2 tbsp sugar, or less to taste",
          "1 tsp baking powder",
          "A pinch of salt",
          "1/4 cup milk",
          "1 tbsp ghee or butter, melted",
          "2 to 3 tbsp water, as needed",
        ],
      },
    ],
    method: [
      "Mix the rice flour, cocoa, coffee, sugar, baking powder and salt in a greased mug or small microwave-safe bowl.",
      "Add the milk and the melted ghee, then enough water to make a smooth, thick batter. Thick, not runny: it should drop off the spoon rather than pour.",
      "Microwave for two to three minutes, checking at two. It is done when the top is set and a knife comes out clean.",
      "Or steam it instead: cover and steam on low to medium heat for twenty to twenty-five minutes, in a dosa maker or a covered pan.",
      "Eat it warm, out of the mug.",
    ],
    notes: [
      "On the raising agent: baking powder is the one to use, and it works on its own. Baking soda will not, because it needs an acid to react with and there is none in this batter. If baking soda is all you have, add a teaspoon of lemon juice or vinegar with it, and stir it in at the last moment before cooking. Without that you get a flat cake with a faintly soapy taste.",
      "For the lightest result, use half a teaspoon of baking powder plus a quarter teaspoon of Eno, stirring the Eno in right at the end and cooking immediately.",
      "The microwave gives a softer, fluffier cake. Steaming gives a denser, more traditional one. Rice flour is denser than wheat either way, so do not expect a sponge.",
      "A little vanilla improves it considerably if you have some. Chocolate chips or chopped nuts on top are worth the trouble.",
      "If you are watching your blood sugar, halve the sugar, add nuts for a little protein and fat, and have it after a meal rather than on an empty stomach.",
    ],
    relatedTopics: [
      "rice-and-roti",
      "anti-inflammatory-swaps-indian-kitchen",
      "diabetes-what-is-happening",
    ],
    guides: [],
  },
  {
    slug: "besan-chilla",
    title: "Besan chilla (gram flour pancake)",
    tag: "Breakfast",
    category: "Food & energy",
    summary:
      "A savoury pancake that takes ten minutes, needs no soaking or fermenting, and carries real protein.",
    keyPoints: [
      "About 10 minutes start to finish, no soaking and no fermenting.",
      "About five grams of protein per chilla. Useful, though gram flour is still mostly carbohydrate.",
      "Vegetables go straight into the batter, so it is a whole breakfast.",
      "Soft to chew, which suits anyone with dental trouble.",
      "Makes a good light dinner as well as breakfast.",
    ],
    serves: "2 (4 chillas)",
    prepTime: "10 minutes",
    prepTimeIso: "PT10M",
    intro: [
      "This is the breakfast to know if you are trying to get more protein into the morning without much effort. Gram flour is already in the house, nothing needs soaking the night before, and the whole thing takes about as long as making tea.",
      "It is also soft, which matters more than people admit. Anyone with sore gums, loose dentures or a dry mouth finds toast and biscuits hard work, and quietly eats less protein as a result.",
    ],
    ingredients: [
      {
        items: [
          "1 cup gram flour (besan)",
          "1 small onion, finely chopped",
          "1 small tomato, finely chopped",
          "A handful of spinach or coriander, chopped",
          "1 green chilli, chopped, optional",
          "1/2 tsp turmeric",
          "1/2 tsp cumin",
          "Salt to taste",
          "About 1 cup water",
          "Oil for cooking",
        ],
      },
    ],
    method: [
      "Put the gram flour in a bowl with the turmeric, cumin and salt. Add water a little at a time, whisking, until you have a smooth batter about the thickness of cream. Lumps now are lumps later, so take a moment over it.",
      "Stir in the onion, tomato, greens and chilli. Let it sit for five minutes if you have time; it is fine if you do not.",
      "Heat a little oil in a pan over medium heat. Pour in a ladleful and spread it gently outwards into a round.",
      "Cook for two to three minutes until the edges lift and the underside is golden, then turn and give it another minute or two.",
      "Serve hot with curd or a coriander chutney.",
    ],
    notes: [
      "For more protein still, whisk two tablespoons of curd into the batter, or serve it with a bowl of curd rather than chutney.",
      "Grated bottle gourd or carrot disappears into the batter and adds fibre without changing the taste much.",
      "The batter keeps in the fridge for a day, so making double is worth the effort.",
      "If you are watching your blood sugar, this is a good breakfast: reasonable protein, high fibre and slower to raise it than bread or poha.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
      "diabetes-what-is-happening",
    ],
    guides: [],
  },
  {
    slug: "moong-dal-dhokla",
    title: "Dhokla made with moong dal",
    tag: "Snack",
    category: "Food & energy",
    summary:
      "Steamed, soft, high in protein and not fried. The snack to have with tea instead of the packet.",
    keyPoints: [
      "Steamed rather than fried, and genuinely high in protein.",
      "Soft and easy to chew, which suits most people at 70.",
      "Keeps for two days, so one batch covers several teatimes.",
      "Replaces the biscuits and namkeen that tea usually comes with.",
      "Needs soaking, so start it the night before.",
    ],
    serves: "4",
    prepTime: "20 minutes, plus soaking overnight",
    prepTimeIso: "PT20M",
    intro: [
      "Tea is where most of the unhelpful eating of the day happens. Biscuits, namkeen, something fried, eaten without much thought. Having a batch of dhokla in the fridge changes that without requiring any willpower.",
      "Made with moong dal rather than gram flour it is higher in protein and lighter on the stomach, and because it is steamed there is no oil in it to speak of.",
    ],
    ingredients: [
      {
        items: [
          "1 cup split yellow moong dal",
          "2 tbsp curd",
          "1 inch ginger and 1 green chilli, ground to a paste",
          "1/2 tsp turmeric",
          "Salt to taste",
          "1 tsp fruit salt (Eno) or 1/2 tsp baking soda with 1 tsp lemon juice",
        ],
      },
      {
        group: "For the tempering",
        items: [
          "1 tbsp oil",
          "1 tsp mustard seeds",
          "A few curry leaves",
          "1 tbsp chopped coriander",
          "1 tbsp grated coconut, optional",
        ],
      },
    ],
    method: [
      "Soak the moong dal in plenty of water for four hours or overnight. Drain it well.",
      "Grind it with the curd and a very little water to a smooth, thick batter. Stir in the ginger and chilli paste, turmeric and salt, and leave it to rest for twenty minutes.",
      "Grease a steamer plate. Bring water to the boil in your steamer or a covered pan.",
      "Stir the fruit salt into the batter, mix gently for a few seconds only, and pour it straight into the plate. It must go into the steam immediately or the rise is lost.",
      "Steam for twelve to fifteen minutes, until a knife comes out clean. Let it cool a little before cutting into squares.",
      "Heat the oil, add mustard seeds, and when they pop add the curry leaves. Pour over the dhokla and scatter with coriander and coconut.",
    ],
    notes: [
      "The fruit salt is what makes it rise, and it works for seconds rather than minutes, so have everything ready before you add it.",
      "It keeps two days covered in the fridge. Steam for two minutes to freshen, or eat at room temperature.",
      "Serve with a coriander and mint chutney rather than a sweet one if blood sugar is a consideration.",
      "Soft, moist and easy to swallow, which makes it one of the better snacks for anyone with a dry mouth or dentures.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
      "xerostomia-dry-mouth",
    ],
    guides: [],
  },
  {
    slug: "ragi-and-moong-porridge",
    title: "Ragi and moong porridge",
    tag: "Breakfast",
    category: "Food & energy",
    summary:
      "A warm breakfast with calcium from the ragi and protein from the dal. Gentle on the stomach and easy to chew.",
    keyPoints: [
      "Ragi is one of the better plant sources of calcium.",
      "Adding moong dal turns a carbohydrate porridge into a protein one.",
      "Warm, soft and easy to digest, which suits early mornings and poor appetite.",
      "Takes about fifteen minutes with no soaking if you use flour.",
      "Can be sweet or savoury; the savoury version raises blood sugar less.",
    ],
    serves: "2",
    prepTime: "15 minutes",
    prepTimeIso: "PT15M",
    intro: [
      "Ragi porridge is a familiar breakfast and it is usually mostly carbohydrate. Adding a little moong dal changes what it does: you get the calcium of the ragi and enough protein to actually see you through to lunch.",
      "It is also warm, soft and undemanding, which matters on mornings when appetite is poor or chewing is uncomfortable.",
    ],
    ingredients: [
      {
        items: [
          "1/4 cup ragi (finger millet) flour",
          "2 tbsp split yellow moong dal",
          "2 cups water or milk, or a mixture",
          "A pinch of salt",
        ],
      },
      {
        group: "To finish, savoury",
        items: [
          "1/2 tsp cumin",
          "A little chopped coriander",
          "Buttermilk or curd on the side",
        ],
      },
      {
        group: "Or to finish, sweet",
        items: [
          "1 tsp jaggery or sugar",
          "A pinch of cardamom",
          "A few chopped almonds",
        ],
      },
    ],
    method: [
      "Dry roast the moong dal in a pan for two or three minutes until it smells nutty, then grind it coarsely. This can be done in advance and kept in a jar.",
      "Mix the ragi flour and the ground dal with half a cup of cold water, whisking until completely smooth. Starting cold is what prevents lumps.",
      "Bring the remaining water or milk to a simmer in a pan, then pour in the paste slowly, stirring the whole time.",
      "Cook on low heat for eight to ten minutes, stirring often, until it thickens and loses any raw smell.",
      "Finish savoury with cumin and coriander, or sweet with a little jaggery, cardamom and almonds.",
    ],
    notes: [
      "Roasting and grinding a large batch of moong dal at once makes this a five-minute breakfast on the day.",
      "Milk rather than water adds more protein and calcium again.",
      "The savoury version raises blood sugar noticeably less than the sweet one, and is worth trying even if it sounds odd at first.",
      "A handful of chopped almonds or a spoon of ground flaxseed on top adds protein, fibre and healthy fat.",
    ],
    relatedTopics: [
      "bone-health-after-menopause",
      "nutrition-basics",
      "rice-and-roti",
    ],
    guides: [],
  },
  {
    slug: "sprouted-moong-salad",
    title: "Sprouted moong salad",
    tag: "Salad",
    category: "Food & energy",
    summary:
      "Raw, crunchy and about fourteen grams of protein a bowl. Sprouting makes the dal easier to digest.",
    keyPoints: [
      "Around fourteen grams of protein in a good bowlful.",
      "Sprouting increases the vitamins and makes moong easier on the stomach.",
      "No cooking at all once the sprouts are ready.",
      "Steam them briefly if raw sprouts do not agree with you.",
      "Keeps in the fridge, so make enough for two or three days.",
    ],
    serves: "2",
    prepTime: "10 minutes, plus 2 days sprouting",
    prepTimeIso: "PT10M",
    intro: [
      "This is about the cheapest protein there is, and one of the easiest. Whole green moong sprouts in two days on a kitchen counter with no equipment, and a bowl of it carries as much protein as an egg and a half, with fibre the egg does not have.",
      "Sprouting is not only tradition. It increases certain vitamins and makes the dal considerably easier to digest, which matters if pulses have tended to trouble you.",
    ],
    ingredients: [
      {
        group: "To sprout",
        items: [
          "1 cup whole green moong",
        ],
      },
      {
        group: "For the salad",
        items: [
          "1 small onion, finely chopped",
          "1 tomato, chopped",
          "1 small cucumber, chopped",
          "1 green chilli, chopped, optional",
          "Juice of half a lemon",
          "1/2 tsp roasted cumin powder",
          "Salt and black pepper",
          "Chopped coriander",
          "1 tbsp grated coconut or roasted peanuts, optional",
        ],
      },
    ],
    method: [
      "Rinse the moong and soak it in plenty of water for eight hours or overnight.",
      "Drain it completely, tie it loosely in a clean damp cloth or put it in a covered container with air holes, and leave it somewhere warm.",
      "Rinse and drain once a day. Small white tails appear within a day or two. That is it; they are ready.",
      "If raw sprouts do not suit you, steam them for four or five minutes, which keeps the crunch and makes them gentler.",
      "Toss the sprouts with the onion, tomato, cucumber, chilli, lemon, cumin, salt and pepper. Scatter with coriander and the coconut or peanuts.",
    ],
    notes: [
      "Steaming briefly is worth doing for anyone with a delicate stomach, and for anyone whose immunity is low, where raw sprouts are best avoided altogether.",
      "Peanuts or roasted chana on top push the protein higher still.",
      "This travels well in a box and keeps two days in the fridge, so it solves several lunches at once.",
      "Eat it before the rice rather than after, which blunts the rise in blood sugar from the meal.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
      "rice-and-roti",
    ],
    guides: [],
  },
  {
    slug: "paneer-bhurji",
    title: "Paneer bhurji",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Ten minutes, soft to eat, and around eighteen grams of protein a portion. The fastest protein in the house.",
    keyPoints: [
      "About eighteen grams of protein per portion.",
      "Ten minutes, and nothing needs soaking or planning.",
      "Soft, so it suits sore gums, dentures or a dry mouth.",
      "Works for breakfast, lunch or dinner equally.",
      "Tofu can replace the paneer if you are avoiding dairy.",
    ],
    serves: "2",
    prepTime: "10 minutes",
    prepTimeIso: "PT10M",
    intro: [
      "When somebody tells me they cannot manage enough protein, this is the recipe I reach for. Paneer needs no preparation, it cooks in minutes, and a modest portion carries more protein than most people get in a whole breakfast.",
      "It is also soft and moist, which is not a small thing. A great deal of high-protein food is chewy, and chewy food is quietly dropped by anyone with dental trouble.",
    ],
    ingredients: [
      {
        items: [
          "200 g paneer, crumbled",
          "1 onion, finely chopped",
          "1 tomato, finely chopped",
          "1 green chilli, chopped, optional",
          "1/2 inch ginger, grated",
          "1/2 tsp turmeric",
          "1/2 tsp cumin seeds",
          "1/2 tsp coriander powder",
          "Salt to taste",
          "1 tbsp oil",
          "Chopped coriander to finish",
        ],
      },
    ],
    method: [
      "Heat the oil in a pan and add the cumin seeds. When they darken slightly, add the onion and cook until soft and just golden.",
      "Add the ginger and chilli, stir for half a minute, then the tomato, turmeric, coriander powder and salt.",
      "Cook until the tomato collapses and the mixture pulls together, three or four minutes.",
      "Crumble in the paneer and stir gently to coat. Cook for two minutes only. Longer makes paneer rubbery, which is the one mistake to avoid.",
      "Finish with coriander and eat with a flatbread, or on its own with a salad.",
    ],
    notes: [
      "Tofu works in place of paneer and brings the saturated fat down considerably. Press out the water first.",
      "Adding a handful of peas, chopped spinach or grated carrot lifts the fibre without changing the character.",
      "Paneer is high in protein and also in saturated fat, so a modest portion alongside vegetables suits most people better than a large one alone.",
      "This is one of the better things to eat within a couple of hours after a movement class.",
    ],
    relatedTopics: [
      "muscle-as-your-bodys-engine",
      "eating-before-and-after-exercise",
      "nutrition-basics",
    ],
    guides: [],
  },
  {
    slug: "oats-and-moong-chilla",
    title: "Oats and moong chilla",
    tag: "Breakfast",
    category: "Food & energy",
    summary:
      "Soluble fibre from the oats, protein from the dal, and no fermenting. Good for cholesterol and for blood sugar.",
    keyPoints: [
      "Oats bring the soluble fibre that helps with cholesterol.",
      "Moong dal turns it from a carbohydrate breakfast into a balanced one.",
      "No fermenting and no waiting, unlike idli or dosa batter.",
      "Soft and quick, and it reheats badly so make what you will eat.",
      "One of the better breakfasts if you are watching blood sugar.",
    ],
    serves: "2 (4 chillas)",
    prepTime: "15 minutes, plus 30 minutes soaking",
    prepTimeIso: "PT15M",
    intro: [
      "Oats usually arrive at breakfast as something sweet and milky, which wastes them. Their real value is soluble fibre, the kind that helps carry cholesterol out, and that works just as well in something savoury.",
      "Combined with moong dal you get fibre and protein in one pan, which is a considerably better start to the day than either alone.",
    ],
    ingredients: [
      {
        items: [
          "1/2 cup rolled oats",
          "1/2 cup split yellow moong dal",
          "1 small onion, finely chopped",
          "1 carrot, grated",
          "A handful of coriander, chopped",
          "1 green chilli, chopped, optional",
          "1/2 tsp cumin",
          "Salt to taste",
          "Water as needed",
          "Oil for cooking",
        ],
      },
    ],
    method: [
      "Soak the moong dal in water for thirty minutes. Drain.",
      "Grind the oats to a coarse powder, then grind the drained dal with a little water to a smooth paste. Mix the two with enough water to make a batter the thickness of cream.",
      "Stir in the onion, carrot, coriander, chilli, cumin and salt.",
      "Heat a little oil in a pan over medium heat, pour in a ladleful and spread it gently into a round.",
      "Cook two to three minutes a side, until golden. Serve hot with curd or chutney.",
    ],
    notes: [
      "Grinding a batch of oats to powder in advance saves five minutes every morning.",
      "A spoon of curd in the batter makes it softer and adds a little more protein.",
      "Eat these fresh. They go leathery on reheating, so make what you will actually eat.",
      "Between the oats and the dal this is a genuinely useful breakfast for anyone working on cholesterol or blood sugar.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "rice-and-roti",
      "diabetes-what-is-happening",
    ],
    guides: [],
  },
  {
    slug: "khichdi-with-extra-dal",
    title: "Khichdi with extra dal",
    tag: "Main",
    category: "Food & energy",
    summary:
      "The comfort food of choice when unwell or tired, made properly so it carries protein rather than just starch.",
    keyPoints: [
      "Most khichdi is mostly rice. This one shifts the ratio towards dal.",
      "Soft, warm and easy to digest, which is why it suits illness and recovery.",
      "One pot, minimal effort, and it keeps.",
      "Add vegetables and it becomes a complete meal.",
      "The single most useful thing to know how to make for a poor appetite.",
    ],
    serves: "3",
    prepTime: "30 minutes",
    prepTimeIso: "PT30M",
    intro: [
      "Khichdi is what everybody eats when they are unwell, tired or have no appetite, and the usual version is mostly rice with a token handful of dal. That gets you comfort and very little protein at exactly the time your body needs it most.",
      "Shifting the ratio, equal dal to rice or more dal than rice, changes what it does without changing what it is. It still tastes like khichdi. It just feeds you properly.",
    ],
    ingredients: [
      {
        items: [
          "3/4 cup split yellow moong dal",
          "1/2 cup rice",
          "1 small carrot, diced",
          "A handful of peas or chopped beans",
          "1 tomato, chopped",
          "1/2 tsp turmeric",
          "1 inch ginger, grated",
          "Salt to taste",
          "4 cups water",
        ],
      },
      {
        group: "For the tempering",
        items: [
          "1 tbsp ghee",
          "1 tsp cumin seeds",
          "A pinch of asafoetida",
          "A few curry leaves",
        ],
      },
    ],
    method: [
      "Rinse the dal and rice together until the water runs clear.",
      "Put them in a pressure cooker or heavy pan with the vegetables, turmeric, ginger, salt and water.",
      "Cook for three or four whistles, or simmer covered for about twenty-five minutes, until everything is soft and collapsing together. It should be loose rather than stiff; add hot water if it thickens too much.",
      "Heat the ghee in a small pan, add the cumin, let it darken, then the asafoetida and curry leaves.",
      "Pour the tempering over the khichdi and stir through. Serve hot with curd.",
    ],
    notes: [
      "A bowl of curd alongside adds protein again, and the two together are gentle on the stomach.",
      "For someone recovering from illness or with a poor appetite, this is the meal to make: soft, warm, protein-containing and easy to eat small amounts of often.",
      "It thickens as it sits. Loosen with hot water rather than serving it stiff, which is harder to swallow.",
      "The ghee is not optional in flavour terms and a spoonful is entirely fine. It is the quantity, not the ghee, that ever matters.",
    ],
    relatedTopics: [
      "muscle-as-your-bodys-engine",
      "nutrition-basics",
      "xerostomia-dry-mouth",
    ],
    guides: [],
  },
  {
    slug: "tofu-and-vegetable-stir-fry",
    title: "Tofu and vegetable stir fry",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Plant protein with no saturated fat, on the table in fifteen minutes.",
    keyPoints: [
      "Tofu brings protein without the saturated fat of paneer.",
      "Fifteen minutes, one pan.",
      "Soy is useful for cholesterol as well as for protein.",
      "Press the tofu first or it will not brown.",
      "Any vegetables in the fridge will do.",
    ],
    serves: "2",
    prepTime: "15 minutes",
    prepTimeIso: "PT15M",
    intro: [
      "Tofu tends to be dismissed as bland, and that is almost always a technique problem rather than an ingredient problem. Pressed properly and cooked hot enough to brown, it holds flavour well and behaves much like paneer.",
      "It is worth having in the rotation because it gives you the protein of paneer without the saturated fat, and soy has a useful part to play if you are working on cholesterol.",
    ],
    ingredients: [
      {
        items: [
          "200 g firm tofu, cut into cubes",
          "1 onion, sliced",
          "1 capsicum, sliced",
          "1 carrot, sliced thin",
          "A handful of beans or cabbage, sliced",
          "2 cloves garlic, chopped",
          "1 inch ginger, chopped",
          "1 tbsp soy sauce",
          "1/2 tsp black pepper",
          "1 tbsp oil",
          "Salt to taste",
        ],
      },
    ],
    method: [
      "Wrap the tofu in a clean cloth, put a plate and something heavy on top, and leave it fifteen minutes. This is the step that decides whether it browns or steams.",
      "Heat the oil in a wide pan until properly hot. Add the tofu in one layer and leave it alone for two or three minutes so it colours, then turn and colour the other side. Lift it out.",
      "In the same pan cook the garlic and ginger for half a minute, then add the vegetables. Keep the heat high and keep them moving; they want four or five minutes and should stay with some bite.",
      "Return the tofu, add the soy sauce, pepper and a little salt, and toss for a minute.",
      "Serve on its own, or with a small serving of rice.",
    ],
    notes: [
      "Pressing the tofu matters more than anything else here. Skip it and you get a pale, wet result.",
      "Soy sauce is salty, so taste before adding more salt, particularly if blood pressure is a consideration.",
      "Soy chunks, soaked and squeezed dry, work in place of tofu and are cheaper.",
      "Eating the tofu and vegetables before the rice blunts the rise in blood sugar.",
    ],
    relatedTopics: [
      "soy-milk-and-plant-milks",
      "muscle-as-your-bodys-engine",
      "rice-and-roti",
    ],
    guides: [],
  },
  {
    slug: "chana-chaat",
    title: "Chana chaat",
    tag: "Snack",
    category: "Food & energy",
    summary:
      "Chickpeas, onion, tomato and lemon. Ten minutes, no cooking, and around twelve grams of protein.",
    keyPoints: [
      "Around twelve grams of protein in a bowl.",
      "No cooking at all if you use tinned or pre-boiled chana.",
      "High in fibre, which is useful for cholesterol as well as digestion.",
      "A proper snack that replaces the fried ones.",
      "Better after an hour in the fridge, so it suits making ahead.",
    ],
    serves: "2",
    prepTime: "10 minutes",
    prepTimeIso: "PT10M",
    intro: [
      "This is the snack to keep in the fridge if you are trying to stop eating namkeen with tea. It takes ten minutes, needs no cooking if you have tinned or already-boiled chana, and it is filling in a way that fried things are not.",
      "A bowl carries about as much protein as two eggs, with a good deal of fibre alongside.",
    ],
    ingredients: [
      {
        items: [
          "2 cups boiled or tinned chickpeas (kabuli chana), drained",
          "1 onion, finely chopped",
          "1 tomato, chopped",
          "1 small cucumber, chopped",
          "1 green chilli, chopped, optional",
          "Juice of one lemon",
          "1 tsp roasted cumin powder",
          "1/2 tsp chaat masala",
          "Salt and black pepper",
          "Plenty of chopped coriander",
          "1 tbsp pomegranate seeds, optional",
        ],
      },
    ],
    method: [
      "If using dried chana, soak overnight and pressure cook until soft. Tinned is entirely fine and much faster; rinse it well.",
      "Tip the chana into a bowl with the onion, tomato and cucumber.",
      "Add the lemon juice, cumin, chaat masala, salt and pepper, and mix.",
      "Taste and adjust; it wants to be sharp rather than shy.",
      "Scatter with coriander and pomegranate, and chill for half an hour if you can before eating.",
    ],
    notes: [
      "Better after an hour in the fridge, so make it in the morning for the evening.",
      "A spoon of curd stirred in makes it creamier and adds a little more protein.",
      "Chaat masala is quite salty, so go easy on additional salt if blood pressure matters.",
      "Kala chana works just as well and is higher in fibre still.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
      "prebiotics-and-probiotics",
    ],
    guides: [],
  },
  {
    slug: "arbi-with-chana-dal",
    title: "Arbi with chana dal",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Colocasia on its own is mostly starch. Cooked with chana dal it becomes a proper meal.",
    keyPoints: [
      "Arbi alone is starchy. The chana dal is what makes this worth eating.",
      "About twelve grams of protein a portion, and plenty of fibre.",
      "Soft once cooked, so it suits anyone who finds chewing hard.",
      "Boil the arbi first or it turns slimy and sticky in the pan.",
      "Chana dal is slow to raise blood sugar, which helps balance the arbi.",
    ],
    serves: "3",
    prepTime: "35 minutes, plus soaking",
    prepTimeIso: "PT35M",
    intro: [
      "Arbi is a favourite in a great many households and it is, on its own, largely starch. Eaten as a sabzi with rice or roti it makes a meal that is carbohydrate on carbohydrate, which is the commonest problem with Indian vegetarian plates.",
      "Cooking it with chana dal solves that without changing the character of the dish. You keep the arbi you like and you get a serving of protein and fibre alongside it.",
    ],
    ingredients: [
      {
        items: [
          "250 g arbi (colocasia)",
          "1/2 cup chana dal, soaked 2 hours",
          "1 onion, chopped",
          "1 tomato, chopped",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp coriander powder",
          "1/2 tsp cumin seeds",
          "1/2 tsp ajwain (carom seeds)",
          "Salt to taste",
          "2 tbsp oil",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Boil the arbi whole until a knife goes in easily, about fifteen minutes. Cool, peel and cut into thick slices. Boiling first is what stops it going slimy.",
      "Pressure cook the soaked chana dal with a little salt and turmeric for three whistles, until soft but still holding its shape. Drain any excess water and keep it.",
      "Heat the oil, add the cumin and ajwain, then the onion. Cook until golden.",
      "Add the ginger garlic paste, tomato, remaining turmeric, coriander powder and salt. Cook until the tomato breaks down.",
      "Add the arbi slices and let them brown a little on the base of the pan without stirring too much. Then fold in the chana dal and a splash of the cooking water, and simmer five minutes. Finish with coriander.",
    ],
    notes: [
      "The ajwain is not decoration here. Arbi is heavy for some people and carom seeds genuinely help with that.",
      "Boiling the arbi before frying is the whole trick. Raw arbi in hot oil goes sticky and stays sticky.",
      "Serve with one roti rather than two, and let the dal and the vegetables carry the plate.",
      "If arbi disagrees with you, the same method works well with raw banana or yam.",
    ],
    relatedTopics: [
      "rice-and-roti",
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
    ],
    guides: [],
  },
  {
    slug: "gatte-ki-sabzi",
    title: "Gatte ki sabzi",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Steamed gram flour dumplings in a curd gravy. Useful protein for a dish that needs no vegetables at all.",
    keyPoints: [
      "Gram flour is roughly a fifth protein, so this carries more than most flour-based dishes.",
      "The gatte are steamed or boiled, not fried, in this version.",
      "Soft in the gravy, so easy to eat.",
      "Needs no fresh vegetables, which suits a day when the fridge is bare.",
      "Keep the heat low when the curd goes in or it will split.",
    ],
    serves: "3",
    prepTime: "35 minutes",
    prepTimeIso: "PT35M",
    intro: [
      "Rajasthani cooking worked out long ago how to eat well without fresh vegetables, and gatte is the best example. Gram flour dumplings in a curd gravy, made from two things that keep in any kitchen.",
      "Worth being accurate about what it gives you. Gram flour is roughly a fifth protein and well over half carbohydrate, so this is not a protein dish in the way that dal, paneer or soya chunks are. It carries useful protein for something made of flour, and the curd adds more. Treat it as a good main rather than a protein source.",
      "The traditional version fries the gatte. Boiling or steaming them works just as well, keeps the dish considerably lighter, and makes it a good deal softer to eat.",
    ],
    ingredients: [
      {
        group: "For the gatte",
        items: [
          "1 cup gram flour (besan)",
          "2 tbsp curd",
          "1 tbsp oil",
          "1/2 tsp turmeric",
          "1/2 tsp red chilli powder",
          "1/2 tsp ajwain",
          "Salt to taste",
        ],
      },
      {
        group: "For the gravy",
        items: [
          "1 cup curd, whisked smooth",
          "1 onion, finely chopped",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp coriander powder",
          "1/2 tsp cumin seeds",
          "2 tbsp oil",
          "Salt to taste",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Mix all the gatte ingredients into a firm dough with a very little water. It should hold together and not be sticky.",
      "Roll into thin logs about the thickness of a finger. Boil them in water for twelve to fifteen minutes until they float and feel firm. Lift out, cool, and cut into pieces. Keep the cooking water.",
      "Heat the oil, add cumin, then onion, and cook until golden. Add the ginger garlic paste and the dry spices with a splash of water so they do not burn.",
      "Take the pan off the heat for a moment. Add the whisked curd slowly, stirring constantly. Return to low heat and keep stirring until it comes together. This is where it splits if you rush it.",
      "Add the gatte and a cup of the reserved cooking water, simmer for five minutes, and finish with coriander.",
    ],
    notes: [
      "The curd must go in off the heat and be stirred continuously. Adding cold curd to a hot pan is how it curdles.",
      "The gatte cooking water is full of flavour. Use it for the gravy rather than plain water.",
      "Boiled rather than fried keeps this light enough to eat on an ordinary evening rather than only at a wedding.",
      "Because the besan is mostly carbohydrate, keep the roti to one and add a bowl of curd or a dal alongside if this is the main dish of the day.",
    ],
    relatedTopics: [
      "muscle-as-your-bodys-engine",
      "nutrition-basics",
      "prebiotics-and-probiotics",
    ],
    guides: [],
  },
  {
    slug: "handvo",
    title: "Handvo",
    tag: "Main",
    category: "Food & energy",
    summary:
      "A savoury baked cake of lentils, rice and vegetables. Makes a whole meal and keeps for days.",
    keyPoints: [
      "Three dals plus rice, so the protein is complete rather than partial.",
      "Vegetables are baked into it, so it is a meal rather than a side.",
      "Baked or steamed, not fried.",
      "Keeps three days and travels well, which suits cooking once.",
      "Needs overnight fermenting, so plan it a day ahead.",
    ],
    serves: "4",
    prepTime: "45 minutes, plus soaking and fermenting",
    prepTimeIso: "PT45M",
    intro: [
      "Handvo is the Gujarati answer to cooking once and eating for three days. Lentils and rice ground together and fermented, vegetables folded in, then baked into a savoury cake with a crisp crust.",
      "Combining dals with rice is not only tradition; it makes the protein more complete than either would be alone. With the vegetables in it, a slice is a genuine meal rather than something to eat alongside one.",
    ],
    ingredients: [
      {
        items: [
          "1 cup rice",
          "1/4 cup toor dal",
          "1/4 cup chana dal",
          "1/4 cup split yellow moong dal",
          "1/2 cup curd",
          "1 cup grated bottle gourd, squeezed dry",
          "1 carrot, grated",
          "1 tsp ginger and green chilli paste",
          "1/2 tsp turmeric",
          "Salt to taste",
          "1 tsp fruit salt (Eno)",
        ],
      },
      {
        group: "For the tempering",
        items: [
          "2 tbsp oil",
          "1 tsp mustard seeds",
          "1 tsp sesame seeds",
          "A pinch of asafoetida",
          "A few curry leaves",
        ],
      },
    ],
    method: [
      "Soak the rice and all three dals together for four hours. Drain and grind with the curd and a little water to a coarse batter, slightly thicker than dosa batter.",
      "Cover and leave overnight in a warm place to ferment. It should smell pleasantly sour and have risen a little.",
      "Stir in the bottle gourd, carrot, ginger and chilli paste, turmeric and salt.",
      "Heat the oil in an oven-safe pan, add mustard and sesame seeds and the curry leaves. Pour half the tempering into the batter and stir.",
      "Add the fruit salt, mix briefly, pour the batter into the pan over the remaining tempering, and bake at 180C for thirty to thirty-five minutes until firm with a browned top. Or cook covered on a very low flame for about twenty-five minutes.",
      "Cool a little before cutting into squares.",
    ],
    notes: [
      "Squeeze the water out of the bottle gourd properly or the batter goes loose and the handvo stays wet in the middle.",
      "It keeps three days in the fridge and is good cold, warm or briefly reheated, which makes it a genuinely useful thing to have made.",
      "Any vegetable works: cabbage, peas, spinach, grated beetroot. It is a good way to use what is left in the fridge.",
      "A slice with a bowl of curd is a complete meal, and the fermenting makes it easier to digest than the ingredients suggest.",
    ],
    relatedTopics: [
      "prebiotics-and-probiotics",
      "muscle-as-your-bodys-engine",
      "nutrition-basics",
    ],
    guides: [],
  },
  {
    slug: "moong-dal-idli",
    title: "Idli made with moong dal",
    tag: "Breakfast",
    category: "Food & energy",
    summary:
      "Steamed, soft and fermented, with more protein than the usual rice idli.",
    keyPoints: [
      "More dal than the usual recipe, so more protein per idli.",
      "Steamed and very soft, the easiest breakfast to chew and swallow.",
      "Fermenting makes it easier to digest and better for the gut.",
      "Needs planning a day ahead, but then makes several breakfasts.",
      "Eat with sambar rather than only chutney and the protein goes up again.",
    ],
    serves: "4",
    prepTime: "20 minutes, plus soaking and fermenting",
    prepTimeIso: "PT20M",
    intro: [
      "Standard idli is mostly rice, which makes it soft and comforting and not very sustaining. Shifting the ratio towards dal keeps everything people like about it and adds the protein that was missing.",
      "It is also the gentlest thing on this list to eat. Steamed, soft and moist, it suits sore gums, dentures and a dry mouth better than almost anything else.",
    ],
    ingredients: [
      {
        items: [
          "1 cup split yellow moong dal",
          "1/2 cup urad dal",
          "1/2 cup rice or idli rava",
          "1/2 tsp fenugreek seeds",
          "Salt to taste",
          "Oil for greasing",
        ],
      },
    ],
    method: [
      "Soak the moong dal, urad dal, rice and fenugreek seeds together in plenty of water for five or six hours.",
      "Drain and grind to a smooth, thick batter, adding water a little at a time. It should drop off the spoon rather than pour.",
      "Add salt, cover, and leave in a warm place overnight to ferment. It should rise and smell pleasantly sour.",
      "Stir the batter gently, once, without knocking the air out. Grease the idli plates and fill them about three quarters full.",
      "Steam for ten to twelve minutes, until a knife comes out clean. Let them stand two minutes before removing.",
    ],
    notes: [
      "The batter is ready when it has risen and smells sour. In cold weather leave it inside the oven with the light on.",
      "Stir gently before steaming. Beating the fermented batter knocks out the air and the idlis come out dense.",
      "Have them with sambar rather than only coconut chutney; the dal in the sambar adds real protein.",
      "Batter keeps three days in the fridge, so one grinding gives several breakfasts.",
    ],
    relatedTopics: [
      "prebiotics-and-probiotics",
      "xerostomia-dry-mouth",
      "nutrition-basics",
    ],
    guides: [],
  },
  {
    slug: "lobia-curry",
    title: "Lobia (black-eyed peas) curry",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Black-eyed peas need no soaking and cook fast, which makes them the easiest pulse to keep in the rotation.",
    keyPoints: [
      "Around thirteen grams of protein a portion.",
      "No overnight soaking needed, unlike most pulses.",
      "High in fibre and folate, and easy on most stomachs.",
      "Cooks in half an hour from dry, faster from tinned.",
      "Better the next day, so it suits making ahead.",
    ],
    serves: "3",
    prepTime: "30 minutes",
    prepTimeIso: "PT30M",
    intro: [
      "Most pulses require thinking about the night before, which is the main reason people fall back on the same two dals. Lobia does not. An hour of soaking is plenty and it will cook without any at all if you have the patience.",
      "It is also gentler on the stomach than rajma or chole, which matters if pulses have given you trouble.",
    ],
    ingredients: [
      {
        items: [
          "1 cup lobia (black-eyed peas)",
          "1 onion, finely chopped",
          "2 tomatoes, chopped",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp coriander powder",
          "1/2 tsp garam masala",
          "1/2 tsp cumin seeds",
          "Salt to taste",
          "2 tbsp oil",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Rinse the lobia and soak for an hour if you have time. Pressure cook with salt and turmeric and three cups of water for four or five whistles, until soft but not collapsing.",
      "Heat the oil in a pan, add cumin seeds, then the onion, and cook until properly golden. Rushing this step is why curries taste flat.",
      "Add the ginger garlic paste, cook a minute, then the tomatoes, coriander powder and salt. Cook until the oil separates at the edges.",
      "Add the cooked lobia with its water, mash a few against the side of the pan to thicken the gravy, and simmer ten minutes.",
      "Stir in the garam masala, finish with coriander, and serve with rice or one roti.",
    ],
    notes: [
      "Mashing a few peas against the pan thickens the gravy without cream or flour.",
      "It is genuinely better the next day, so make enough for two meals.",
      "A bowl of curd alongside adds protein and cools the dish.",
      "Tinned black-eyed peas work perfectly well; rinse them and skip straight to the gravy.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
      "rice-and-roti",
    ],
    guides: [],
  },
  {
    slug: "soya-chunk-curry",
    title: "Nutri soya chunk curry",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Dry soya chunks are about half protein, which is exceptional for a cupboard staple.",
    keyPoints: [
      "Dry weight they beat paneer comfortably. Once soaked they take up water, so a cooked portion is closer to paneer than the raw figure suggests.",
      "Inexpensive and they keep in the cupboard for months.",
      "Squeeze them out properly or the curry tastes of nothing.",
      "Soy is useful for cholesterol as well as protein.",
      "Soft once cooked, so easy to eat.",
    ],
    serves: "3",
    prepTime: "25 minutes",
    prepTimeIso: "PT25M",
    intro: [
      "Soya chunks, sold as nutri or nutrela, are the cheapest concentrated protein most Indian kitchens have access to, and they sit in the cupboard for months. Dry, they are about half protein, which almost nothing else in the cupboard matches.",
      "The reason people dislike them is almost always preparation. Soaked and then squeezed out properly, they take up whatever they are cooked in. Left soggy, they taste of warm water.",
    ],
    ingredients: [
      {
        items: [
          "1 cup soya chunks",
          "1 onion, finely chopped",
          "2 tomatoes, pureed",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp coriander powder",
          "1/2 tsp red chilli powder",
          "1/2 tsp garam masala",
          "1/2 tsp cumin seeds",
          "Salt to taste",
          "2 tbsp oil",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Boil the soya chunks in salted water for five minutes, then drain. Rinse under cold water and squeeze each handful firmly between your palms until no water comes out. This step decides whether the dish is good.",
      "Heat the oil, add cumin, then onion, and cook until golden brown.",
      "Add the ginger garlic paste, then the tomato puree, turmeric, coriander and chilli powder and salt. Cook until the oil separates.",
      "Add the squeezed chunks and stir so they take up the masala. Add a cup of hot water and simmer for ten minutes so they soften and absorb it.",
      "Finish with garam masala and coriander.",
    ],
    notes: [
      "The squeezing is the whole recipe. Wet chunks dilute the masala and taste bland no matter what you add.",
      "Soya is worth including if you are working on cholesterol, alongside its protein.",
      "Adding peas, capsicum or spinach turns it into a fuller meal.",
      "If you have thyroid trouble, soya in ordinary food amounts is generally fine, but it is worth mentioning to your doctor if you eat it daily.",
    ],
    relatedTopics: [
      "soy-milk-and-plant-milks",
      "muscle-as-your-bodys-engine",
      "nutrition-basics",
    ],
    guides: [],
  },
  {
    slug: "mixed-sprouts-usal",
    title: "Usal: sprouted bean curry",
    tag: "Main",
    category: "Food & energy",
    summary:
      "A Maharashtrian everyday curry of sprouted beans, light and high in protein.",
    keyPoints: [
      "Sprouting raises the vitamins and makes the beans easier to digest.",
      "Around fourteen grams of protein a portion.",
      "Lighter than a rajma or chole gravy, so good for an evening meal.",
      "Any sprouted bean works: moong, matki, chana, val.",
      "Cook it thin and eat it as a soup if appetite is poor.",
    ],
    serves: "3",
    prepTime: "25 minutes",
    prepTimeIso: "PT25M",
    intro: [
      "Usal is what Maharashtrian households eat on ordinary days: sprouted beans in a thin, spiced gravy, eaten with rice or bread or on its own from a bowl.",
      "It is lighter than the heavier bean curries, which makes it a better evening meal for most people at 70, and the sprouting means it sits considerably easier than the same beans unsprouted.",
    ],
    ingredients: [
      {
        items: [
          "2 cups mixed sprouts (moong, matki, chana)",
          "1 onion, finely chopped",
          "1 tomato, chopped",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp goda masala or garam masala",
          "1/2 tsp mustard seeds",
          "1/2 tsp cumin seeds",
          "A pinch of asafoetida",
          "A few curry leaves",
          "Salt to taste",
          "2 tbsp oil",
          "2 tbsp grated coconut",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Heat the oil, add mustard seeds and let them pop, then cumin, asafoetida and curry leaves.",
      "Add the onion and cook until soft and golden, then the ginger garlic paste for a minute.",
      "Add the tomato, turmeric and salt, and cook until it breaks down.",
      "Add the sprouts and two cups of water. Simmer covered for twelve to fifteen minutes, until the sprouts are tender but not mushy.",
      "Stir in the masala and the coconut, simmer two minutes more, and finish with coriander. It should be thin enough to spoon.",
    ],
    notes: [
      "Keep it thin. Usal is meant to be brothy rather than thick, and a thinner version is easier to eat when appetite is low.",
      "Any sprouted bean works. Matki (moth beans) is the traditional one, but mixed sprouts from the market are fine.",
      "If raw or lightly cooked sprouts have troubled you before, cook these a few minutes longer; the dish is forgiving.",
      "A bowl of this with one roti is a complete meal with no other protein needed.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "muscle-as-your-bodys-engine",
      "prebiotics-and-probiotics",
    ],
    guides: [],
  },
  {
    slug: "steamed-moong-dal-vada",
    title: "Vada: steamed moong dal vada",
    tag: "Snack",
    category: "Food & energy",
    summary:
      "All the flavour of a vada with none of the deep frying. Steamed, soft and protein-rich.",
    keyPoints: [
      "Steamed rather than deep fried, so light enough for every day.",
      "Moong dal makes it genuinely high in protein.",
      "Soft, which suits anyone who finds fried food hard to chew.",
      "Needs soaking, so start it in the morning for the evening.",
      "Good hot or at room temperature with chutney.",
    ],
    serves: "4",
    prepTime: "25 minutes, plus soaking",
    prepTimeIso: "PT25M",
    intro: [
      "Vada is one of the things people give up when they are told to eat less fried food, and it is a real loss. Steaming the same batter gives you something soft, savoury and satisfying that can be eaten on an ordinary Tuesday rather than saved for festivals.",
      "It is also, because it is mostly dal, one of the higher protein snacks you can make.",
    ],
    ingredients: [
      {
        items: [
          "1 cup split yellow moong dal",
          "1 inch ginger, grated",
          "1 green chilli, chopped, optional",
          "A pinch of asafoetida",
          "1/2 tsp cumin seeds",
          "2 tbsp chopped coriander",
          "1 tbsp grated coconut, optional",
          "Salt to taste",
          "1/2 tsp fruit salt (Eno)",
          "Oil for greasing",
        ],
      },
    ],
    method: [
      "Soak the moong dal for three to four hours. Drain it thoroughly.",
      "Grind to a thick, coarse paste with as little water as you can manage. Too much water and they will not hold their shape.",
      "Stir in the ginger, chilli, asafoetida, cumin, coriander, coconut and salt.",
      "Grease a steamer plate or small moulds. Add the fruit salt to the batter, mix for a few seconds only, and spoon into the moulds at once.",
      "Steam for twelve to fifteen minutes until firm and a knife comes out clean. Serve warm with coriander chutney.",
    ],
    notes: [
      "Grind with as little water as possible. A loose batter gives flat, wet vadas.",
      "The fruit salt works for seconds, so have the steamer hot and the moulds greased before you add it.",
      "They keep two days in the fridge and steam back to life in two minutes.",
      "Serve with a green chutney rather than a sweet one, and with a bowl of curd if you want the protein higher still.",
    ],
    relatedTopics: [
      "muscle-as-your-bodys-engine",
      "xerostomia-dry-mouth",
      "nutrition-basics",
    ],
    guides: [],
  },
  {
    slug: "egg-bhurji",
    title: "Egg bhurji",
    tag: "Breakfast",
    category: "Food & energy",
    summary:
      "Two eggs, ten minutes, twelve grams of complete protein. Hard to beat for effort against return.",
    keyPoints: [
      "About twelve grams of protein from two eggs, and it is complete protein.",
      "Ten minutes, and everything is already in the kitchen.",
      "Eggs carry B12, which vegetarian diets are often short of after 60.",
      "Soft and moist, so easy to eat with dental trouble.",
      "For most people the old cholesterol worry about eggs has been overstated.",
    ],
    serves: "2",
    prepTime: "10 minutes",
    prepTimeIso: "PT10M",
    intro: [
      "If you eat eggs, this is the most protein you will get for ten minutes of effort anywhere on this site. Egg protein is complete, meaning it contains all the building blocks your body cannot make, which most single plant foods do not manage alone.",
      "Eggs also carry vitamin B12, and shortage of that is common after 60, particularly on a largely vegetarian diet and more so for anyone on long-term acidity medication.",
    ],
    ingredients: [
      {
        items: [
          "4 eggs",
          "1 onion, finely chopped",
          "1 tomato, finely chopped",
          "1 green chilli, chopped, optional",
          "1/2 inch ginger, grated",
          "1/4 tsp turmeric",
          "1/2 tsp cumin seeds",
          "Salt and black pepper",
          "1 tbsp oil",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Beat the eggs lightly with a little salt and pepper and set aside.",
      "Heat the oil, add cumin seeds, then the onion, and cook until soft and golden.",
      "Add the ginger and chilli, then the tomato and turmeric, and cook until the tomato softens.",
      "Turn the heat low and pour in the eggs. Stir slowly and constantly, taking them off while they still look slightly underdone, because they carry on cooking in the pan.",
      "Finish with coriander and eat at once, with a roti or on its own.",
    ],
    notes: [
      "Low heat and taking them off early is the whole difference between soft bhurji and rubbery bhurji.",
      "For most healthy people an egg a day is fine. The old advice to avoid eggs for cholesterol has been considerably softened, though if you have been given specific advice by your doctor, follow that rather than this.",
      "Adding chopped spinach, peas or capsicum with the onion stretches it and adds fibre.",
      "One of the best things to eat within a couple of hours of a movement class.",
    ],
    relatedTopics: [
      "muscle-as-your-bodys-engine",
      "zinc-and-minerals-after-60",
      "eating-before-and-after-exercise",
    ],
    guides: [],
  },
  {
    slug: "fish-curry-light",
    title: "Fish curry, the lighter way",
    tag: "Main",
    category: "Food & energy",
    summary:
      "Complete protein and omega-3 fats, in a tomato and curd gravy rather than a heavy coconut one.",
    keyPoints: [
      "Around twenty-five grams of complete protein a portion.",
      "Oily fish carries omega-3 fats, which matter for heart and brain.",
      "Soft, needing almost no chewing, which suits most people at 70.",
      "Cooks in fifteen minutes; fish is ruined by long cooking.",
      "Two portions of fish a week is a sensible target if you eat it.",
    ],
    serves: "3",
    prepTime: "25 minutes",
    prepTimeIso: "PT25M",
    intro: [
      "If you eat fish, it is among the most useful things on your plate after 60. Complete protein, very easy to chew and swallow, and in the oily varieties, the omega-3 fats associated with heart and brain health.",
      "This version uses a tomato and curd base rather than a thick coconut gravy, which keeps it lighter for an ordinary evening without losing anything that matters.",
    ],
    ingredients: [
      {
        items: [
          "500 g firm fish, cut into pieces (surmai, rohu, pomfret or any local fish)",
          "2 onions, finely chopped",
          "2 tomatoes, pureed",
          "1/2 cup curd, whisked smooth",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp coriander powder",
          "1/2 tsp red chilli powder",
          "1/2 tsp mustard seeds",
          "A few curry leaves",
          "Salt to taste",
          "2 tbsp oil",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Rub the fish with a little salt and turmeric and leave it fifteen minutes while you make the gravy.",
      "Heat the oil, add mustard seeds and curry leaves, then the onion, and cook until properly golden.",
      "Add the ginger garlic paste, then the tomato puree and the dry spices with salt. Cook until the oil separates at the edges.",
      "Take the pan off the heat and stir in the whisked curd slowly. Return to low heat and cook two minutes without letting it boil hard.",
      "Slide in the fish, add half a cup of hot water, cover and simmer eight to ten minutes only, until the fish flakes. Do not stir much or it will break. Finish with coriander.",
    ],
    notes: [
      "Fish needs minutes, not tens of minutes. Overcooked fish goes dry and tough, which is the usual reason people think they dislike it.",
      "Oily fish such as surmai, bangda or sardines carry the most omega-3. Freshwater fish are still excellent protein even with less of it.",
      "The curd goes in off the heat, as with any curd gravy, or it will split.",
      "Two portions a week is a reasonable aim. If you have gout or kidney disease, check with your doctor about which fish and how much.",
    ],
    relatedTopics: [
      "muscle-as-your-bodys-engine",
      "heart-attack-signs-in-women",
      "dementia-what-it-is-and-lowering-risk",
    ],
    guides: [],
  },
  {
    slug: "jackfruit-kathal-with-chana-dal",
    title: "Jackfruit (kathal) with chana dal",
    tag: "Main",
    category: "Food & energy",
    summary:
      "A good vegetable with a meaty texture, and honestly not a protein source. The dal is what makes it a meal.",
    keyPoints: [
      "Raw jackfruit has a meaty texture and very little protein.",
      "It is often sold as a meat substitute. That is about texture, not nutrition.",
      "Cooked with chana dal it becomes a genuinely balanced dish.",
      "High in fibre and filling, which suits a smaller appetite.",
      "Oil your hands before cutting it or the sap will stick to everything.",
    ],
    serves: "3",
    prepTime: "40 minutes",
    prepTimeIso: "PT40M",
    intro: [
      "Raw jackfruit, kathal, has become fashionable as a meat substitute, and it is worth being clear about what that means. The resemblance is texture. Jackfruit is a vegetable, mostly carbohydrate and fibre, with roughly two grams of protein per hundred. It is nothing like meat nutritionally.",
      "That is not a criticism of it. It is a good vegetable, filling and satisfying. It simply needs a protein cooked with it, and chana dal does the job while suiting the flavours.",
    ],
    ingredients: [
      {
        items: [
          "400 g raw jackfruit (kathal), cut into chunks",
          "1/2 cup chana dal, soaked 2 hours",
          "2 onions, finely chopped",
          "2 tomatoes, chopped",
          "1 tsp ginger garlic paste",
          "1/2 tsp turmeric",
          "1 tsp coriander powder",
          "1/2 tsp garam masala",
          "1/2 tsp cumin seeds",
          "Salt to taste",
          "3 tbsp oil",
          "Chopped coriander",
        ],
      },
    ],
    method: [
      "Oil your hands and the knife before cutting the jackfruit. The sap is sticky and does not come off easily otherwise.",
      "Pressure cook the soaked chana dal with salt and turmeric for three whistles, until soft but still holding shape. Keep the water.",
      "Boil or steam the jackfruit chunks for ten minutes until a knife goes in with slight resistance. Drain.",
      "Heat the oil, add cumin, then the onion, and cook until well browned. Add the ginger garlic paste, tomato and dry spices, and cook until the oil separates.",
      "Add the jackfruit and let it take colour for five minutes. Fold in the chana dal with a splash of its water, simmer ten minutes, and finish with garam masala and coriander.",
    ],
    notes: [
      "Oiling your hands before cutting is not optional advice. The sap is genuinely difficult to remove.",
      "Tinned green jackfruit in brine saves a great deal of work. Rinse it well and skip the boiling.",
      "This is one of the better dishes for a small appetite: the fibre makes a modest portion satisfying.",
      "Do not count this as your protein for the day. The dal is doing that work, so keep it generous.",
    ],
    relatedTopics: [
      "nutrition-basics",
      "classic-indian-dishes-for-seniors",
      "rice-and-roti",
    ],
    guides: [],
  },
  {
    slug: "vegetable-and-tofu-soup",
    title: "Vegetable and tofu soup",
    tag: "Soup",
    category: "Food & energy",
    summary:
      "A soft, warm bowl with cabbage, spring onion and silken tofu. Nothing to chew, which matters more than it sounds.",
    keyPoints: [
      "Soft all the way through, so it suits a sore mouth, a bad tooth or a poor appetite.",
      "About eight grams of protein a bowl. A light meal rather than a large one.",
      "Silken tofu needs no preparation at all beyond spooning it in.",
      "Ready in twenty minutes from a cold pan.",
      "Easy to make less salty than any packet soup.",
    ],
    serves: "2",
    prepTime: "20 minutes",
    prepTimeIso: "PT20M",
    intro: [
      "There are days when chewing is the problem: a mouth ulcer, a tooth that is being difficult, a chest infection, or simply no appetite. What usually happens on those days is tea and a biscuit, and then nothing until evening.",
      "This is the bowl for those days. Everything in it is soft, it is warm, and it still has real protein in it because of the tofu. It is also genuinely quick, which matters when you are not feeling like cooking.",
      "Silken tofu is the soft kind sold in a block in water or in a carton. It breaks apart in the soup, which is what you want here; firm tofu stays in cubes and is better in a stir-fry.",
    ],
    ingredients: [
      {
        group: "For the soup",
        items: [
          "1 tsp olive oil or sesame oil",
          "1 small onion, finely chopped",
          "2 cloves garlic, crushed",
          "2 spring onions, white and green parts kept separate",
          "2 cups cabbage, shredded",
          "1 carrot, cut into thin rounds, optional",
          "4 cups water or a light vegetable stock",
          "250 g silken tofu",
          "Salt and black pepper",
        ],
      },
      {
        group: "For flavour, use what you have",
        items: [
          "1 tsp soy sauce or tamari",
          "1/4 tsp miso paste, if you have it",
          "1/2 tsp chilli flakes or a little red chilli paste",
          "1 tsp sesame seeds",
          "A sheet of nori seaweed, crushed, optional",
        ],
      },
    ],
    method: [
      "Warm the oil in a pan. Add the onion, garlic and the white part of the spring onion with a pinch of salt, and cook gently until the onion softens and goes translucent.",
      "Add the cabbage and carrot and cook for two or three minutes, stirring, until they start to wilt.",
      "Add the water or stock, along with the soy sauce, miso if using, and chilli. Bring it to a simmer.",
      "Spoon in the silken tofu in large pieces. Do not stir hard from here or it will disappear; move it gently.",
      "Simmer for five minutes. Add the sesame seeds, the green part of the spring onion and the crushed seaweed if using.",
      "Taste for salt, remembering the soy sauce has already brought some, and serve hot.",
    ],
    notes: [
      "About eight grams of protein a bowl. That is a light meal, not a large one, so have it with a chilla or some toast if it is your main meal.",
      "Miso, gochujang and nori are worth having if you can find them, and the soup works perfectly well without any of them. Plain garlic, chilli and soy sauce is a good bowl.",
      "Soy sauce and miso are both salty. If you watch your blood pressure, use one or the other and add no further salt.",
      "It does not keep well once the tofu is in, so make what you will eat.",
    ],
    relatedTopics: [
      "protein-at-every-meal",
      "xerostomia-dry-mouth",
      "nutrition-basics",
    ],
    guides: [],
  },
  {
    slug: "walnut-and-orange-salad",
    title: "Walnut and orange salad",
    tag: "Salad",
    category: "Food & energy",
    summary:
      "Orange, cucumber and toasted walnuts with a lemon dressing. Vitamin C and good fats rather than protein, and pleasant to eat.",
    keyPoints: [
      "Vitamin C from the orange, which helps the body absorb iron from the rest of the meal.",
      "Walnuts bring omega-3 fats, the kind most Indian diets are short of.",
      "No cooking beyond toasting the nuts for a few minutes.",
      "Soft to eat if you chop the cucumber small.",
      "Not a protein dish. Have it alongside one rather than as the meal.",
    ],
    serves: "2",
    prepTime: "15 minutes",
    prepTimeIso: "PT15M",
    intro: [
      "Orange and cucumber sound like an odd pair and are not. The orange is sweet and sharp, the cucumber is cool and does nothing much, and the walnuts give it something to bite on.",
      "It is worth being accurate about what this is. It is not a protein dish. What it does bring is vitamin C, the omega-3 fats in walnuts, and a reason to eat a whole fruit rather than drink a juice. Put it next to paneer, curd or a chilla and you have a proper meal.",
      "The vitamin C matters more than it looks. Eaten with a meal, it helps your body take up iron from the dal and greens in it, which is a real advantage for anyone running low.",
    ],
    ingredients: [
      {
        group: "For the salad",
        items: [
          "2 oranges, peeled and broken into segments",
          "1 cucumber, peeled and cut into chunks",
          "1/3 cup walnuts",
          "A little grated parmesan or crumbled feta, optional",
          "A few mint leaves, optional",
        ],
      },
      {
        group: "For the dressing",
        items: [
          "Juice of 1 lemon",
          "2 tbsp extra virgin olive oil",
          "Salt and black pepper",
          "1/2 tsp sugar or honey",
        ],
      },
    ],
    method: [
      "Toast the walnuts in a dry pan over a low flame for three or four minutes until they smell nutty. Watch them; they burn in the time it takes to answer the phone. Tip them out to cool and break them up roughly.",
      "Peel the oranges and pull them into segments. There is no need to cut them smaller unless you want to.",
      "Peel the cucumber and cut it into chunks. Smaller pieces if chewing is difficult.",
      "Whisk the lemon juice, olive oil, salt, pepper and sugar together until it comes together.",
      "Put the orange and cucumber in a bowl, pour over the dressing and turn it gently.",
      "Scatter the walnuts over the top, along with the cheese and mint if using, and eat soon after.",
    ],
    notes: [
      "Toasted walnuts are the everyday version. Candied walnuts, made by slow-roasting them with a spoon of sugar, are very good and are a sweet, so keep them for when it is a treat rather than every day.",
      "Strawberries and spinach work in place of the orange and cucumber, with a balsamic dressing and feta instead of parmesan, if that is what you have.",
      "Grinding a whole lemon, peel and all, and passing it through a sieve gives a sharper dressing with more of the oils from the skin in it.",
      "Scatter the nuts on at the last minute or they soften.",
      "Oranges are high in potassium. If you have kidney disease and have been told to watch potassium, this is one to ask about.",
    ],
    relatedTopics: [
      "protein-at-every-meal",
      "nutrition-basics",
      "anti-inflammatory-basics",
    ],
    guides: [],
  },
  {
    slug: "cucumber-salad-with-peanuts-and-sesame",
    title: "Cucumber salad with peanuts and sesame",
    tag: "Salad",
    category: "Food & energy",
    summary:
      "Cucumber, crushed roasted peanuts, garlic and sesame. Five minutes, no cooking, and it goes with almost anything.",
    keyPoints: [
      "About seven grams of protein a portion, from the peanuts.",
      "Five minutes and no heat at all.",
      "Everything in it keeps in the house, so it can be made on short notice.",
      "Crushing the peanuts rather than leaving them whole makes it easier to chew.",
      "Good beside dal and rice, which is the meal that most needs something fresh.",
    ],
    serves: "2",
    prepTime: "5 minutes",
    prepTimeIso: "PT5M",
    intro: [
      "This is the salad to make when there is dal and rice for dinner and nothing fresh on the table. It takes five minutes and needs nothing cooked.",
      "The peanuts are doing the work. Roasted and crushed, they bring about seven grams of protein and enough fat to make it satisfying rather than just crunchy. Garlic and sesame do the rest.",
    ],
    ingredients: [
      {
        items: [
          "2 cucumbers, peeled and cut into chunks or thin slices",
          "1/3 cup roasted peanuts, crushed",
          "2 cloves garlic, crushed",
          "1 tbsp soy sauce or tamari",
          "1 tsp sesame oil",
          "1/2 tsp sugar",
          "1 tsp sesame seeds",
          "A pinch of chilli flakes, optional",
          "Salt, only if needed",
        ],
      },
    ],
    method: [
      "Peel the cucumbers and cut them into chunks, or thin slices if you prefer. Chunks hold their crunch longer.",
      "Crush the roasted peanuts roughly, with a rolling pin or the base of a heavy glass. Do not grind them to powder.",
      "Mix the crushed garlic, soy sauce, sesame oil, sugar and chilli flakes in the bottom of a bowl.",
      "Add the cucumber and turn it through the dressing.",
      "Scatter the peanuts and sesame seeds over and eat straight away, while the cucumber is still crisp.",
    ],
    notes: [
      "Soy sauce is salty, so taste before adding any salt at all. If you watch your blood pressure, use half the soy sauce and make up the flavour with lemon.",
      "Raw garlic is strong. A smaller clove, or garlic warmed for a moment in the sesame oil, is gentler on the stomach.",
      "Cucumber releases water as it sits, so dress it when you are ready to eat rather than in advance.",
      "Add cubes of paneer or tofu and it becomes a light meal rather than a side dish.",
    ],
    relatedTopics: [
      "protein-at-every-meal",
      "nutrition-basics",
      "classic-indian-dishes-for-seniors",
    ],
    guides: [],
  },
  {
    slug: "avocado-chocolate-mousse",
    title: "Avocado chocolate mousse",
    tag: "Dessert",
    category: "Food & energy",
    summary:
      "Three ingredients, a food processor and two minutes. A chocolate pudding built on good fat rather than cream.",
    keyPoints: [
      "Three ingredients and no cooking at all.",
      "Soft and cold, so it suits a sore mouth or a poor appetite.",
      "Built on the fats in avocado rather than cream and butter.",
      "Far less sugar than any shop-bought dessert.",
      "A dessert, not a protein food. Curd stirred in changes that.",
    ],
    serves: "2",
    prepTime: "5 minutes",
    prepTimeIso: "PT5M",
    intro: [
      "A ripe avocado blended with cocoa tastes of chocolate and not at all of avocado, which surprises people every time. It comes out thick and glossy, like a set pudding.",
      "It is still a dessert. What it is not is a bowl of cream and refined sugar, and for anyone who wants something sweet after dinner without it undoing the meal, that is the useful difference.",
    ],
    ingredients: [
      {
        items: [
          "1 ripe avocado",
          "1 tbsp cocoa powder, unsweetened",
          "1 tbsp sugar, honey or a few soft dates",
          "1/2 tsp coconut oil, optional",
          "A pinch of salt",
          "A splash of milk, if it needs loosening",
        ],
      },
    ],
    method: [
      "Use an avocado that gives slightly when you press it. A hard one will not blend smooth and a black one tastes bitter.",
      "Scoop the flesh into a food processor or small mixer jar.",
      "Add the cocoa, the sugar or dates, the coconut oil if using, and the pinch of salt.",
      "Blend until completely smooth, stopping to scrape the sides down. It should look like set chocolate pudding.",
      "If it is too stiff, add a splash of milk and blend again.",
      "Spoon into two small bowls and chill for half an hour before eating.",
    ],
    notes: [
      "Start with one tablespoon of cocoa and taste. More makes it darker and more bitter, which some people prefer.",
      "A couple of spoons of thick curd blended in makes it lighter and adds some protein, and it will not keep as long.",
      "Coconut oil is largely saturated fat, so half a teaspoon for gloss is the right amount rather than a spoonful.",
      "It browns on the surface within a day, as cut avocado does. Press cling film onto the top, and eat it the same day.",
      "Avocado is high in potassium. If you have kidney disease and have been told to watch potassium, ask before adding this in.",
    ],
    relatedTopics: [
      "protein-at-every-meal",
      "nutrition-basics",
      "xerostomia-dry-mouth",
    ],
    guides: [],
  },
];

export const recipesBySlug = new Map(recipes.map((r) => [r.slug, r]));

export function getRecipe(slug: string) {
  return recipesBySlug.get(slug) ?? null;
}
